### ISSUE TITLE
Repeater: Footer Height

### ISSUE THREAD

**Issue by mbeard** [ExactTarget/fuelux-mctheme#102]
Computed height of the footer should be 31px. It is currently 43px and we need to adjust height, padding, etc. to reduce to the correct height.

**Comment by interactivellama** [comment]
I will PR it. The fix for me was the following. It makes the footer the same height as the panel footer with buttons in it.

```
	.repeater-footer {
		padding: 8px 10px 8px 10px; 		// makes footer equal with .panel footer
		min-height: 0;
	}
```

**Comment by swilliamset** [comment]
We need to do what we can to not be hardcoding these paddings etc. The computed height should be the result of using the appropriate font size variable and predefined padding variables. If the variables are unable to reproduce the attached screenshot from the controls library design than the design needs to be revisited.
![screen shot 2015-01-07 at 12 38 25 pm](https://cloud.githubusercontent.com/assets/347227/5650180/1cd334ea-966a-11e4-9be9-81b5386e68af.png)

**Comment by interactivellama** [comment]
I agree about setting a height. That screenshot looks like 10px padding on the left side, 15px on the right and 3px on top and bottom.

**Comment by interactivellama** [comment]
I'm hoping that we can get Jamin and Rachel to watch our issues as they come up and comment.

**Comment by swilliamset** [comment]
@interactivellama would you forward on to them as needed or should @scott-joe-williams since he has been taking on the style guide UXA liaison role?

**Comment by BenjaminNeilDavis** [comment]
@swilliamset @interactivellama  I think we could for sure use variables but the variables and the way they are set arent exactly the way they should be. For instance the variable I could and should use in this instance would be @padding-medium-vertical (comes from bootstrap-override/variables.less). If you look at these medium vertical is currently set to 12px and large vertical is set to 8px. I think these would be perfect to set up if used correctly. Were you thinking something similar?

**Comment by interactivellama** [comment]
If I had to abstract it, I would abstract it out of the repeater something akin to OO's inheritance concept like the following:

```
@footer-padding: 8px 10px 8px 10px;
@footer-span-line-height: 21px;

.footer-with-inputs {
  padding: @footer-padding;

   > span {
    line-height: @footer-span-line-height; // vertical center text
  }
}

.repeater-footer {
  .footer-with-inputs();
}

.panel-footer {
  .footer-with-inputs();
}
```

If I wasn't passing the code on to other dev's, I'd just have multiple classes on the `div`, but we are trying to minimize the complexity of the markup right now.
