### ISSUE TITLE
Repeater: Page Size / Page Menus

### ISSUE THREAD

**Issue by mbeard** [ExactTarget/fuelux-mctheme#103]
The menus for the page size selectlist and the page combobox should be the same width as the element.

Currently:
![screenshot 2015-01-07 11 36 00](https://cloud.githubusercontent.com/assets/467352/5649100/64129688-9661-11e4-978a-2f3395be84b2.png)

Should be:
![screenshot 2015-01-07 11 33 50](https://cloud.githubusercontent.com/assets/467352/5649086/4eae1114-9661-11e4-93c6-fc6cb6232137.png)

**Comment by mbeard** [comment]
Related to https://github.com/ExactTarget/fuelux/issues/948

**Comment by swilliamset** [comment]
resolved in https://github.com/ExactTarget/fuelux/tree/3.5.0 release
