### ISSUE TITLE
Container and Row Padding/Margins out of sync

### ISSUE THREAD

**Issue by mbeard** [ExactTarget/fuelux-mctheme#114]
The container padding is set to 20px, but row margins are at -15px.  This results in alignment issues like this (most notable if the row has a background color).  Check for both `.container` and `.container-fluid` and `.row` class.

![screenshot 2015-01-16 14 23 34]
(https://cloud.githubusercontent.com/assets/467352/5782704/5a679c7e-9d8b-11e4-9cd3-32b42f6d0915.png)

**Comment by interactivellama** [comment]
Fixed by #117.
