### ISSUE TITLE
Allow visual testing in Snippets, Pages to verify not breaking anything on release

### ISSUE THREAD

**Issue by interactivellama** [ExactTarget/fuelux-mctheme#115]
New process:
- Auto-deploy and grunt dist files on Heroku app (Edge server)
- Allow Pages and Snippets to use edge versions from #master (possibly via URL variable, "?edge=true"?) in production versions without deploying pages and snippets.

**Comment by jmgekeler** [comment]
Use edge version from master on both Snippets and Pages by adding the querystring param "edge=1" to the url.
