### ISSUE TITLE
Selectlist: button text color

### ISSUE THREAD

**Issue by mbeard** [ExactTarget/fuelux-mctheme#124]
The button text color is current blue and needs to be changed to the default font color.
![screenshot 2015-01-23 13 03 09](https://cloud.githubusercontent.com/assets/467352/5879850/c5955516-a300-11e4-84e1-609c726c0a2f.png)

**Comment by interactivellama** [comment]
I think it got changed to blue, because it technically is a button and buttons are blue, although I think the dropdowns in the styleguide are black for some reason.

**Comment by mbeard** [comment]
@jamin-hall what's your recommendation for this.  Should the text be the default font color instead of blue for the selectlist?

**Comment by jamin-hall** [comment]
I'd recommend using the default font color.

JAMIN HALL
Lead Interaction Designer | salesforce.com
Mobile: 317-701-4990

**Comment by mbeard** [comment]
This has been resolved.
