### ISSUE TITLE
need overrides for validation states

### ISSUE THREAD

**Issue by swilliamset** [ExactTarget/fuelux-mctheme#131]
http://getbootstrap.com/css/#forms-control-validation

needs style guide feedback first

**Comment by swilliamset** [comment]
styleguide

**Comment by chriscorwin** [comment]
Currently, the closest thing the style guide has seems to be:

![required field notification 2015-02-11 13 17 24](https://cloud.githubusercontent.com/assets/362417/6153131/6b0044c2-b1f0-11e4-8fef-e30446db55b0.png)

Perhaps @jamin-hall can help?

**Comment by cormacmccarthy** [comment]
ok, it sounds like this _maybe shouldn't_ be a part of mc-theme. Especially since the plugin won't be part of either fuelux _or_ the marketing cloud theme.

So, while MCAS will still possibly need guidance on the look/feel of this element, it won't be tied to mctheme or fuelux

**Comment by cormacmccarthy** [comment]
I think what we maybe need to do here is provide a skinned version of the tooltip that people can call on fail.

http://getbootstrap.com/javascript/#tooltips

Something like:
```
$('#element').tooltip({title: 'error message', placement: 'right', trigger: 'focus'}).tooltip('show');
```
Will trigger the tooltip (no markup required)

And then in the styles, something like this would do the trick:

```
input.error .tooltip-arrow, input.error .tooltip-inner {
background-color: red;
}
```

**Comment by swilliamset** [comment]
unless we want to add new classes i recommend we overwrite bs validation classes as well

**Comment by cormacmccarthy** [comment]
agreed.

**Comment by cormacmccarthy** [comment]
This... is already done :|

![image](https://cloud.githubusercontent.com/assets/8006971/6421990/e99585dc-bea1-11e4-821c-6b05bb0b18f9.png)
