### ISSUE TITLE
Checkboxes are "off" in the demo

### ISSUE THREAD

**Issue by vernak2539** [ExactTarget/fuelux-mctheme#132]
see screenshot
![capture](https://cloud.githubusercontent.com/assets/521270/5942792/c419770c-a711-11e4-8c2b-c639a02437fd.PNG)

**Comment by chriscorwin** [comment]
These were fixed in the other fork.

**Comment by interactivellama** [comment]
We need to make sure that the GH-pages branch gets updated though when we release.
