### ISSUE TITLE
Icons for repeater-views too big when not using glyphicon prefix

### ISSUE THREAD

**Issue by chriscorwin** [ExactTarget/fuelux-mctheme#141]
See:

The icons are the correct size when using:

`<span class=“glyphicon glyphicon-gridview-list"></span>`

...but not when using:

`<span class="fuelux-icon fuelux-icon-gridview-list"></span>`

![screenshot 2015-02-02 16 02 47](https://cloud.githubusercontent.com/assets/362417/6009131/f6757a48-aaf4-11e4-911a-8099c920905f.png)

**Comment by swilliamset** [comment]
fixed by #142
