### ISSUE TITLE
Spinbox needs a background color

### ISSUE THREAD

**Issue by jmgekeler** [ExactTarget/fuelux-mctheme#151]
The spinbox needs a white background so it doesn't look disabled when over different colors.

![afe9c7a8-addf-11e4-9414-1ffbea57b8f9](https://cloud.githubusercontent.com/assets/450099/6086696/e65c380c-ae11-11e4-99df-e5ac3c7440b5.png)

**Comment by interactivellama** [comment]
We may want this in the Fuel UX repo.

**Comment by cormacmccarthy** [comment]
lol, nope: https://github.com/ExactTarget/fuelux/issues/1042

**Comment by interactivellama** [comment]
Thanks, @cormacmccarthy
