### ISSUE TITLE
Checkbox not aligned properly

### ISSUE THREAD

**Issue by dkilgore** [ExactTarget/fuelux-mctheme#153]
MCtheme 1.3.4, using markup from http://getfuelux.com/javascript.html#checkbox

Hovering over the checkbox corrects the alignment issue of the checkbox graphic. When not hovered:

![screen shot 2015-02-09 at 11 29 10 am](https://cloud.githubusercontent.com/assets/1205242/6110376/476b52c4-b04f-11e4-97e8-4de6e34bb2ed.png)

```
<div class="checkbox" id="firstExperience">
    <label class="checkbox-custom" data-initialize="checkbox">
        <input class="sr-only" type="checkbox" value="">
        <span class="checkbox-label">{{as-migration-firstExperience-checkBoxMsg}}</span>
    </label>
</div>
```

**Comment by swilliamset** [comment]
resolved in the pending release currently in master (ETA Tues Feb 9)
https://github.com/ExactTarget/fuelux-mctheme/pull/139
