### ISSUE TITLE
repeater: config button is large than view buttons

### ISSUE THREAD

**Issue by swilliamset** [ExactTarget/fuelux-mctheme#156]
![screen shot 2015-02-09 at 3 27 14 pm](https://cloud.githubusercontent.com/assets/347227/6114994/48b81380-b070-11e4-8a66-379d6794f88e.png)

**Comment by chriscorwin** [comment]
This is an issue in fuelux-pages, not in fuelux-mctheme.


See: 
https://github.com/ExactTarget/fuelux-pages/pull/46
