### ISSUE TITLE
Selectlist removed hardcoded value for padding and add variables 

### ISSUE THREAD

**Issue by BenjaminNeilDavis** [ExactTarget/fuelux-mctheme#169]

**Comment by interactivellama** [comment]
I think #170 may have fixed it. Please double check @BenjaminNeilDavis.

Here are [your recent PRs](https://github.com/ExactTarget/fuelux-mctheme/pulls?q=is%3Apr+author%3ABenjaminNeilDavis+is%3Aclosed). Thanks!

**Comment by interactivellama** [comment]
Fixed by #170.
