### ISSUE TITLE
Input validation popover needed

### ISSUE THREAD

**Issue by cormacmccarthy** [ExactTarget/fuelux-mctheme#174]
![image](https://cloud.githubusercontent.com/assets/8006971/6280922/0dd97bca-b884-11e4-8ed4-6c79d43a7fe1.png)

**Comment by chriscorwin** [comment]
OKAY, I'm going to tackle this.

Heay @jamin-hall --- is there any other advice you can give on this, spec-wise?


And for @cmcculloh, where did this specific request come from? Automation Studio? or .... ?


And lastly, for @kevinparkerson and @interactivellama  --- what's the best way to go about this, engineering wise?

Is this a "plugin" ?  A "widget" ?

or... ?

**Comment by cmcculloh** [comment]
@dkilgore for Automation Studio requested this.

**Comment by mbeard** [comment]
This looks like a duplicate of #131

**Comment by cormacmccarthy** [comment]
This will be a separate plugin.

**Comment by interactivellama** [comment]
Even if it is a separate plugin, we would probably want to bower it in and show it off in MCtheme.

**Comment by cormacmccarthy** [comment]
I just realized this is literally a red bootstrap tooltip tied to a form element :)

**Comment by swilliamset** [comment]
Tooltip doesn't align appropriately. Appears to be because of missing relative position wrapper.
![screen shot](https://cloud.githubusercontent.com/assets/347227/6469459/b06e84e6-c1aa-11e4-8248-d339e9f7802d.png)

**Comment by cormacmccarthy** [comment]
new issue #181
