### ISSUE TITLE
Tree control: Expand folder caret not lining up in Firefox

### ISSUE THREAD

**Issue by dkilgore** [ExactTarget/fuelux-mctheme#175]
Looks OK in Chrome, but latest FF (http://fuelux-snippets.herokuapp.com/tree-folder):
![screen shot 2015-02-26 at 10 55 29 am](https://cloud.githubusercontent.com/assets/1205242/6395440/21fbc208-bda6-11e4-9f38-bc4f49d7c42b.png)

**Comment by cormacmccarthy** [comment]
Firefox is mis-applying the :before selector that we are using to place this.

![image](https://cloud.githubusercontent.com/assets/8006971/6422383/ddabed2a-bea5-11e4-8ba8-191654e12494.png)

**Comment by swilliamset** [comment]
Markup in snippet is out of place. 'glyphicon icon-caret` should be inside the `tree-branch-name and not a button.

See recent update to fuelux gh-pages https://github.com/ExactTarget/fuelux/pull/1140
