### ISSUE TITLE
Increase iconography within theme

### ISSUE THREAD

**Issue by interactivellama** [ExactTarget/fuelux-mctheme#18]
Add classes to theme to support icons in SVG format. If you'd like an icon added to this theme, please post and tell us about it's prior use in an ExactTarget application. Thanks.

**Comment by interactivellama** [comment]
No need for @2.x since we are switching to SVG format.

**Comment by mbeard** [comment]
@chriscorwin should we get a list of the next set of icons to release.  Or do you already have that?

**Comment by interactivellama** [comment]
Closing to create a more specific issue.
