### ISSUE TITLE
Update Checkbox and Radio Buttons to use new non-custom styles from Fuel UX

### ISSUE THREAD

**Issue by chriscorwin** [ExactTarget/fuelux-mctheme#184]
Fuel UX is deprecating checkbox and radio buttons, update the theme to use these new rules and style them correctly for the Marketing Cloud.

Don't forget to do documentation too!

**Comment by swilliamset** [comment]
can we break this up into two steps 
 1. adding support for the new structure (1.4.*)
 2. deprecating (1.?.0)

**Comment by chriscorwin** [comment]
Closed, merged.
