### ISSUE TITLE
Folder icons switch the names?

### ISSUE THREAD

**Issue by BenjaminNeilDavis** [ExactTarget/fuelux-mctheme#186]
I was adding the folder icon and to me it seems like the open folder and the regular folder icons names should be switched.

<img src="https://www.evernote.com/shard/s79/sh/8f833d5c-311b-4a23-8e1c-52159004f276/fe6af4af135b7d9093f13e5f74593b88/deep/0/Fuel-UX-3-Icons.png" alt="Fuel%20UX%203%20Icons" />

**Comment by interactivellama** [comment]
@chriscorwin

**Comment by mbeard** [comment]
If you look at the icons on edge, they appear to be correct.  Are you referencing something different than [this](https://fuelux-mctheme.herokuapp.com/less/icons/preview.html)

**Comment by swilliamset** [comment]
current master are labeled correctly 
http://fuelux-mctheme.herokuapp.com/less/icons/preview.html
![screen shot 2015-03-13 at 1 43 42 pm](https://cloud.githubusercontent.com/assets/347227/6643994/112e8dc4-c987-11e4-99ab-fe512de0fbb9.png)
