### ISSUE TITLE
SVG Icons - Should we include the script snippet somewhere in documentation?

### ISSUE THREAD

**Issue by BenjaminNeilDavis** [ExactTarget/fuelux-mctheme#187]
This is the snippet I am referring to:
<img src="https://www.evernote.com/shard/s79/sh/5de51184-68df-4796-958a-ea4be2ac4672/d11dec32e89051e84d71972d5fd1dcb9/deep/0/fuelux-mctheme-preview.html-at-master---ExactTarget-fuelux-mctheme.png" alt="fuelux-mctheme/preview.html%20at%20master%20%C2%B7%20ExactTarget/fuelux-mctheme" />

The SVG icons wont work without it and only people who really know that they exist / how to enable them can use them.

**Comment by interactivellama** [comment]
Aren't the SVG icons [base64 encoded into the main css file](https://github.com/ExactTarget/fuelux-mctheme/blob/master/dist/css/fuelux-mctheme.css#L37)? I'm not sure what you are referring to?

**Comment by BenjaminNeilDavis** [comment]
This is very true. I was going off of http://exacttarget.github.io/fuelux-mctheme/examples/icons/preview.html. It looks like the class names may have changed a little bit which is why I couldn't access them. Is there a different preview file I should be looking at to see all the available icons / class names?

**Comment by interactivellama** [comment]
I don't know of any others. @chriscorwin ?

**Comment by swilliamset** [comment]
@BenjaminNeilDavis @interactivellama can this be closed?

**Comment by swilliamset** [comment]
@chriscorwin please comment on why this snippet exists and close the issue

**Comment by chriscorwin** [comment]
The thing exists because it is part of the default preview HTML file that gets made by the grunt library we are using. We need to customize the template so that it spits out a partial that can be consumed by the living style guide, but since that isn't ready yet it seemed silly to spend a whole bunch of time customizing a template toooo much that will just change anyway.
