### ISSUE TITLE
Include all spritesheet.png icons in SVG format

### ISSUE THREAD

**Issue by interactivellama** [ExactTarget/fuelux-mctheme#232]
Error:
![screenshot 2015-04-07 14 56 26](https://cloud.githubusercontent.com/assets/1290832/7031226/e894ec7c-dd37-11e4-8d89-d53d18eee8c7.png)

This was previously in the theme and has been removed with the creation of the SVG icon set.

The last two on the right need to be added to the SVG icon set. 

![spritesheet-2x](https://cloud.githubusercontent.com/assets/1290832/7031314/8e7cb156-dd38-11e4-8192-9a2dec1dca17.png)

**Comment by gdborton** [comment]
@interactivellama The question mark icons are also missing (and a few others I'd suspect), opened this when I noticed that some icons are referencing the removed spritesheet.  #252
