### ISSUE TITLE
Snippet page problems

### ISSUE THREAD

**Issue by interactivellama** [ExactTarget/fuelux-mctheme#233]
http://fuelux-snippets.herokuapp.com/checkbox-list
![screenshot 2015-04-07 15 31 25](https://cloud.githubusercontent.com/assets/1290832/7031694/71dc506c-dd3b-11e4-87eb-52910ace2d90.png)

Also: http://fuelux-snippets.herokuapp.com/form

**Comment by mbeard** [comment]
The checkbox list snippet is resolved.  Not sure what the issue with the form was, but can you confirm whether it's fixed @interactivellama

**Comment by interactivellama** [comment]
I can confirm it's works for me! Thanks @mbeard. Closing...
