### ISSUE TITLE
Missing icon preview page

### ISSUE THREAD

**Issue by interactivellama** [ExactTarget/fuelux-mctheme#244]
The icon page linked to from `index.html`is not being generated correctly. http://fuelux-mctheme.herokuapp.com/examples/icons/icons.html

I have audited the icon CSS and the final CSS file to know that the correct SVGs are being embedded at this time.

**Comment by chriscorwin** [comment]
I need to understand more about what's going wrong.

Because it builds just fine for me.

That's going to make it tough for *me* to fix, since I don't see it broked.
