### ISSUE TITLE
References to missing .png files

### ISSUE THREAD

**Issue by gdborton** [ExactTarget/fuelux-mctheme#252]
Hello,

I noticed that there are some references in the dist .css files to a spritesheet file that doesn't exist.

[`../img/spritesheet.png`](https://github.com/ExactTarget/fuelux-mctheme/blob/master/dist/css/fuelux-mctheme.css#L208)
[`../img/spritesheet-2x.png`](https://github.com/ExactTarget/fuelux-mctheme/blob/master/dist/css/fuelux-mctheme.css#L227)

I checked bootstrap, fuelux, and mctheme... none of them seem to include this in their dist folders.  If that's the case, I'm wondering what question mark icon we're supposed to be using.

@swilliamset

**Comment by interactivellama** [comment]
It's a bug. We switched to SVGs and that fell through the cracks. We will include these in the next release.

The spritesheet.png files were removed in v1.4.1.
