### ISSUE TITLE
CDN :allthethings:

### ISSUE THREAD

**Issue by cormacmccarthy** [ExactTarget/fuelux-mctheme#253]
Need a CDN source of these things all bundled together:

* jquery
* bootstrap
* fuelux
* fueluxmctheme

Should consider these to be included too:

* underscore
* backbone
* marionette

**Comment by interactivellama** [comment]
Are they all going to latest version?

**Comment by cormacmccarthy** [comment]
Latest version verified to work with our library (so, each time we do a release, whatever version we are using at release time).

The use case is being able to use the CDN for our Platform Apps.

@futuremint

**Comment by interactivellama** [comment]
At the meeting today, the group asked that you and I verify that the performance gain would be worth the bundling at every release, etc.

underscore, backbone, marionette may need to be its own repo, although I do see the release convenience of adding the whole front stack to mctheme, but the purist in us thinks it should be in it's own marketing-cloud-lib repo.

I can place a bundle of CSS on the Fuel CDN soon to test out. We'd probably want to maintain the JS in the fuelux repo if we move forward with this.

**Comment by cormacmccarthy** [comment]
we already bower in underscore, etc, to the library. There would be no reason to change that. The only thing we would be changing is creating an additional grunt task that generates a single bundled JS and single bundled CSS file that includes everything you need to use Fuel UX.

This certainly won't help with first time visit to the first page that uses this, but, if CDNs are actually worth anything at all, this will help with repeat visits if it is done properly (hosted from a consistent static location).

**Comment by interactivellama** [comment]
Do we want moment in this too?

**Comment by interactivellama** [comment]
Please close once "rucksack" is completed, vetted, and uploaded.

**Comment by kevinparkerson** [comment]
http://www.fuelcdn.com/rucksack/1.0.0/
