### ISSUE TITLE
Help Icon missing from mctheme

### ISSUE THREAD

**Issue by dkilgore** [ExactTarget/fuelux-mctheme#263]
Looking for this icon from the mctheme:
![screen shot 2015-04-24 at 10 38 28 am](https://cloud.githubusercontent.com/assets/1205242/7321131/7ea824ac-ea6e-11e4-8c0c-36495c8113de.png)

From http://getfuelux.com/mctheme/index.html#mctheme
![screen shot 2015-04-24 at 10 39 32 am](https://cloud.githubusercontent.com/assets/1205242/7321136/87418d60-ea6e-11e4-9a76-c967ce65f835.png)

It appears this icon didnt get ported.

**Comment by interactivellama** [comment]
A new release will be out this week with SVG version of the help icon. Closing and grouping with issue. #232 Thanks, Dan!
