### ISSUE TITLE
How to test if icons change between versions?

### ISSUE THREAD

**Issue by interactivellama** [ExactTarget/fuelux-mctheme#265]
We don't currently have any QA processes that test if updated icons fail?

The icon sheet in MCtheme examples is generated by the names of the icons we give them which is awesome from "our" standpoint. How do we know that we aren't breaking anything and maintain backwards compatibility with the product teams that we support? I'm trying to prevent having to do a release just because the icon name changed, etc.

@chriscorwin Any suggestions?

One option could be to maintain a legacy copy of `/examples/icons/icons.html` that we could look at with the new icon generation and see if anything is messed up.

**Comment by chriscorwin** [comment]
I wonder if Argus could be used to build and maintain a list of the icons being used?

I wonder if the app teams are consistent enough with icon naming that a non-manual audit would be helpful?

@futuremint

**Comment by interactivellama** [comment]
grunt command calling out to a JSON file from argus which finds each class within icons HTML file? That would be awsum!
