### ISSUE TITLE
Ensure input has `type` attribute in radio, checkbox LESS files.

### ISSUE THREAD

**Issue by chriscorwin** [ExactTarget/fuelux-mctheme#272]
*Note:* This is a sister Fuel UX issue: https://github.com/ExactTarget/fuelux/issues/1271

Reports of using any other type of input _inside_ a `.checkbox` or `.radio` wrapper yields unexpected results because the `input` rules in the LESS files may not always have a `type` attribute on them.

Investigate and fix.

**Comment by interactivellama** [comment]
What type of input is being used within `.radio` or `.checkbox`? 

If it's a text input, it should probably be besides it like the following _which hasn't been exposed in the MC theme_. Maybe they aren't aware of it.

![screenshot 2015-05-04 23 53 36](https://cloud.githubusercontent.com/assets/1290832/7466841/1cc36398-f2b9-11e4-9f51-64a5bc2b0baf.png)


Also, we could use just `[type=checkbox]` without the `input`. What do you think?
