### ISSUE TITLE
spritesheet.png referenced in css file

### ISSUE THREAD

**Issue by jtryan** [ExactTarget/fuelux-mctheme#273]
If spritesheet.png is no longer included, what should this change to? 

.collapse-dropdown .panel .panel-heading .glyphicon-play {
  ....
  background: transparent url(../img/spritesheet.png) no-repeat -176px -16px;
  width: 13px;
  height: 13px;
}
...
.collapse-dropdown .panel .panel-heading a.collapsed .glyphicon-play {
  background: transparent url(../img/spritesheet.png) no-repeat -176px 0;
}

**Comment by interactivellama** [comment]
Thanks for reporting @jtryan. This will be fixed in #274 and released in v1.5.1.

**Comment by interactivellama** [comment]
In master branch with dist bump.
