### ISSUE TITLE
Radios (no javascript version) have blue background

### ISSUE THREAD

**Issue by interactivellama** [ExactTarget/fuelux-mctheme#278]
no-js radios have blue background.

![screenshot 2015-05-05 15 38 12](https://cloud.githubusercontent.com/assets/1290832/7481258/c84cd8c4-f33c-11e4-88bf-243dd00e8e70.png)

Is this because of the [type=radio] change? checkbox appears to be fine.

**Comment by swilliamset** [comment]
duped by https://github.com/ExactTarget/fuelux-mctheme/issues/279 includes links to problematic code
