### ISSUE TITLE
FTUX Needs

### ISSUE THREAD

**Issue by mbeard** [ExactTarget/fuelux-mctheme#282]
For first time user experience, we need to add the following:

1. The help/tips icon needs to be added to our list of icons
![ftux](https://cloud.githubusercontent.com/assets/467352/7520874/f547bec6-f4b7-11e4-82e7-a9d0286a824f.png)

2. We need to add an appropriate class to style bootstrap popovers and popover content
![screenshot 2015-05-07 11 37 31](https://cloud.githubusercontent.com/assets/467352/7520894/15bd7c68-f4b8-11e4-858e-302f6b51c71c.png)
 like so:

**Comment by swilliamset** [comment]
@kevinparkerson please provide an svg to be included in the mctheme icons for @dwaltz to consume in ftux component

**Comment by kevinparkerson** [comment]
I've done the .ai / .svg file portion of this. I've sent it to @dwaltz for him to continue this task.

**Comment by swilliamset** [comment]
gracias senior @kevinparkerson

**Comment by swilliamset** [comment]
FYI the lightbulb icon has been updated in prod. https://mc.exacttarget.com/contactsmeta/images/ftux/InfoTipIcon_32x32.svg

**Comment by kevinparkerson** [comment]
That icon scales poorly, it's strokes have not been set to scale. I can fix this. (also, having that much clearer design helps a ton!)

**Comment by kevinparkerson** [comment]
@dwaltz - @chriscorwin is back, so he will be correcting the lightbulb icon and providing it to you

**Comment by swilliamset** [comment]
closing. styles live within internal component.
