### ISSUE TITLE
Update wizard markup to Fuel UX 3.8 release

### ISSUE THREAD

**Issue by interactivellama** [ExactTarget/fuelux-mctheme#300]
Sync wizard styles with Fuel UX 3.8 release markup changes.

See http://fuelux-mctheme.herokuapp.com/examples/fuelux/fuelux.html#wizard

**Comment by gdborton** [comment]
@interactivellama Should we pin the fuelux dependency a little more tightly so that html/class changes don't disrupt the mctheme?
