### ISSUE TITLE
Wizard steps overflowing.

### ISSUE THREAD

**Issue by jbarngr** [ExactTarget/fuelux-mctheme#304]
![screen shot 2015-06-19 at 10 02 13 pm](https://cloud.githubusercontent.com/assets/915237/8265639/d3b12272-16cf-11e5-970a-283ec1382066.png)
![screen shot 2015-06-19 at 10 00 26 pm](https://cloud.githubusercontent.com/assets/915237/8265640/d4f09050-16cf-11e5-86f5-3b32956eaeef.png)

This is both Firefox and Chrome on Mac. Looks likes most of this is in the FuelUX core but because of using the theme I wanted to bring it up here first.

**Comment by interactivellama** [comment]
Is this in a recent upgrade to Fuel UX 3.8? If so, please review the release notes [concerning the wizard](https://github.com/ExactTarget/fuelux/releases/tag/3.8.0#a-note-about-wizard-markup).

The element `div.steps-container` has been added to the markup. Previously, the `.wizard` wrapper element had the overflow hidden which caused bugs in the content pane.

**Comment by scott-joe-williams** [comment]
@jbarngr if you can, see the release notes Stephen mentioned above. That *may* be your solution. If that doesn't work let me know and I'll check it out. Thanks.

**Comment by jbarngr** [comment]
Just took a look, and yes I didn't update the layout to include ```div.steps-container```. That will solve my issue, but as a principle should we allow the ```div.wizard``` to allow overflows outside of it's bounds? thoughts @interactivellama @scott-joe-williams

**Comment by scott-joe-williams** [comment]
Hm. Well how does it behave with that div? Does it properly scroll and overflow:hidden and all that?

**Comment by interactivellama** [comment]
Issue #1241 with the use of a tall combobox within a content pane being cut off due to the `overflow:hidden`  was the impetus for the change.

**Comment by jbarngr** [comment]
Shouldn't the scrolling be on the interior containers? Meaning that if any scrolling should be handle within the ```div.step-pane`` or ```div.step-container```, in the case of the body.

**Comment by jbarngr** [comment]
@interactivellama to the point of that, I understand that situation, but at what do you force people just to scroll? What do you do if the dropdown goes below the browser edge? Don't they have to scroll at that point anyways?

**Comment by kevinparkerson** [comment]
@jbarngr scrolling should be determined by the content you place within the `div.step-pane` classed elements. We've simply altered the wizard so that it can accommodate all use-cases by not having a default overflow behavior for step-pane content. It is up to the developer, not the wizard, to decide what happens to the step-pane content. If you are experiencing issues with dropdowns inside the wizard, you can use the [dropdown auto-flip](http://getfuelux.com/extensions.html#bundled-extensions-dropdown-autoflip) extension to solve that issue within your application.
