### ISSUE TITLE
New caret button icons

### ISSUE THREAD

**Issue by swilliamset** [ExactTarget/fuelux-mctheme#320]
Please provide inverted and rotate caret icons resulting in the following set

### Current Set

* `.fuelux-icon-caret-down`
* `.fuelux-icon-caret-down-hover`
* `.fuelux-icon-caret-right`
* `.fuelux-icon-caret-right-hover`

#### *-blue alias of current
- [ ] `.fuelux-icon-caret-down-blue` (`.fuelux-icon-caret-down-hover`)
- [ ] `.fuelux-icon-caret-down-blue-hover` (`.fuelux-icon-caret-down`)
- [ ] `.fuelux-icon-caret-right-blue` (`.fuelux-icon-caret-right-hover`)
- [ ] `.fuelux-icon-caret-right-blue-hover` (`.fuelux-icon-caret-right`)

#### inverse directions with rotate css
- [ ] `.fuelux-icon-caret-up` (`.fuelux-icon-caret-up` flip)
- [ ] `.fuelux-icon-caret-up-hover` (`.fuelux-icon-caret-up-hover` flip)
- [ ] `.fuelux-icon-caret-left` (`.fuelux-icon-caret-left` flip)
- [ ] `.fuelux-icon-caret-left-hover` (`.fuelux-icon-caret-left-rotate` flip)
- [ ] `.fuelux-icon-caret-up-blue` (`.fuelux-icon-caret-up-hover` flip)
- [ ] `.fuelux-icon-caret-up-blue-hover` (`.fuelux-icon-caret-up` flip)
- [ ] `.fuelux-icon-caret-left-blue` (`.fuelux-icon-caret-left-hover` flip)
- [ ] `.fuelux-icon-caret-left-blue-hover` (`.fuelux-icon-caret-left` flip)

**Comment by swilliamset** [comment]
Good start keep it up
![pasted_image_at_2015_07_22_01_40_pm_360](https://cloud.githubusercontent.com/assets/347227/8832782/f404ed0c-3078-11e5-8fe9-0e6bf677a6a7.png)

**Comment by TheJaredWilcurt** [comment]
Shouldn't it be flipped instead of rotated so that the gradients match?

Like this:

    .flipVertical {
        -webkit-transform: scaleY(-1);
        transform: scaleY(-1);
        filter: FlipV;
        -ms-filter: "FlipV";
    }

    .fuelux-icon-caret-left-blue {
        .fuelux-icon-caret-right-hover;
        .flipVertical;
        &-hover,
        &:hover {
            .fuelux-icon-caret-right;
            .flipVertical;
        }
    }

Otherwise the faux light-source the gradient is representing wouldn't make sense if both arrows were visible at the same time. Just my thoughts anyways.

**Comment by swilliamset** [comment]
Good point. Thx for the feedback. We'll be sure to flip instead of rotate.

**Comment by TheJaredWilcurt** [comment]
@BenjaminNeilDavis 

See: https://github.com/ExactTarget/fuelux-mctheme/pull/323
