### ISSUE TITLE
Repeater + pillbox display - snippet library

### ISSUE THREAD

**Issue by rachprice** [ExactTarget/fuelux-mctheme#347]
In the Fuel UX snippet library -> Repeater Paired with Pillbox
When an item is selected the name doesn't appear in the pillbox, only the "x" does.

http://fuelux-snippets.herokuapp.com/repeater-pillbox

![repeater pillbox](https://cloud.githubusercontent.com/assets/10350614/9341207/52d327c8-45a9-11e5-87a3-15614466bccb.png)

**Comment by mbeard** [comment]
Closing this item.  It is fixed, but related to a separate project, not MC Theme.
