### ISSUE TITLE
Content icon complexity and compatibility with svg-min

### ISSUE THREAD

**Issue by interactivellama** [ExactTarget/fuelux-mctheme#386]
Some of the latest additional icons for content editor may be incompatible with `svg-min`. An audit may need to be done.

`svg-min` node modules does not like the Illustrator SVG output. Says it's "too complex." I would guess this has to due with compound paths or a gradient.

The best way to debug would be test each icon in the "content editor set" with `svg-min`.

https://github.com/ExactTarget/fuelux-mctheme/issues/351 (non-final design)
http://fuelux-mctheme.herokuapp.com/examples/icons/icons.html (final design)

**Comment by cormacmccarthy** [comment]
@jamin-hall to do deep dive on Illustrator to try and mitigate these sorts of issues.
