### ISSUE TITLE
Audit of icons inside of buttons

### ISSUE THREAD

**Issue by BenjaminNeilDavis** [ExactTarget/fuelux-mctheme#389]
Currently default icon size inside of button is 12px x 12px.
Large is only 13px x 13px (really not much of a difference).

Suggesting possible change to btn-lg icon size to 14px x 14px and a btn-x-lg to be a size of 16px x 16px.

What do you think @jamin-hall ?

**Comment by jamin-hall** [comment]
Stephen Williams and I were looking at that yesterday. I think that would
make sense, but we'd want to make sure we consider how those changes look
with the labels. When I bumped the size up, the label alignment got a
little funky.

On Thu, Sep 10, 2015 at 2:52 PM, Benjamin Davis <notifications@github.com>
wrote:

> Currently default icon size inside of button is 12px x 12px.
> Large is only 13px x 13px (really not much of a difference).
>
> Suggesting possible change to btn-lg icon size to 14px x 14px and a
> btn-x-lg to be a size of 16px x 16px.
>
> What do you think @jamin-hall <https://github.com/jamin-hall> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ExactTarget/fuelux-mctheme/issues/389>.
>



-- 

JAMIN HALL

Lead Interaction Designer | salesforce.com

Mobile: 317-701-4990
