### ISSUE TITLE
Scheduler drop down are too narrow, causing horizontal scrolling

### ISSUE THREAD

**Issue by dkilgore** [ExactTarget/fuelux-mctheme#416]
On repeat monthly or yearly the day dropdown is too narrow, scroll bar overlaps half the numbers.
![screen shot 2015-10-29 at 12 49 33 pm](https://cloud.githubusercontent.com/assets/1205242/10825569/f606c204-7e3b-11e5-98d2-f4fd5a696fd2.png)

**Comment by interactivellama** [comment]
I'm getting this too in FireFox. Looks like it's a side effect of the selectlist's auto resize measurement in Fuel UX.
