### ISSUE TITLE
repeater `list_setSelectedItems` does not select correctly

### ISSUE THREAD

**Issue by swilliamset** [ExactTarget/fuelux-mctheme#445]
Check box not checked and row not highlighted completely.

Requires core work ExactTarget/fuelux#1677

![image](https://cloud.githubusercontent.com/assets/347227/12360024/5c7188ec-bb83-11e5-8af9-12292c66aa35.png)

https://jsfiddle.net/Lw5b1b5e/3/

**Comment by swilliamset** [comment]
On second thought certain this will require core work https://github.com/ExactTarget/fuelux/issues/1677

**Comment by dwaltz** [comment]
This [PR](https://github.com/ExactTarget/fuelux/pull/1681) to the fuelux core repo fixes the issue.
