### ISSUE TITLE
Row action spacing misalignment

### ISSUE THREAD

**Issue by interactivellama** [ExactTarget/fuelux-mctheme#464]
Bug can be viewed at http://fuelux.herokuapp.com/controls/repeater

![screen shot 2016-04-15 at 10 39 04 am](https://cloud.githubusercontent.com/assets/1290832/14564724/da870e00-02f5-11e6-9541-c79a63c08e01.png)

**Comment by swilliamset** [comment]
unable to reproduce in latest mc theme 1.15.4 w/ fuel 3.15.11
