### ISSUE TITLE
Links to demo aren't working

### ISSUE THREAD

**Issue by tacman** [ExactTarget/fuelux-mctheme#470]
View the latest at http://fuelux-mctheme.herokuapp.com/

At the moment, that returns  a 404:

![image](https://cloud.githubusercontent.com/assets/619585/21849339/2b408486-d7d3-11e6-84e8-142e165e8477.png)

**Comment by swilliamset** [comment]
Theme offered primarily as an example and for internal usage. It is no longer recommended for use and only maintained for critical bug fixes. Demo page has been removed.
