### ISSUE TITLE
Datepicker Styling

### ISSUE THREAD

**Issue by mbeard** [ExactTarget/fuelux-mctheme#52]
Need to get updated designs and specifications for this control.

**Comment by chriscorwin** [comment]
What's the status of this?


Currently, datepicker looks like:

![datepicker current 2015-02-11 13 11 34](https://cloud.githubusercontent.com/assets/362417/6153033/93ff69bc-b1ef-11e4-997c-2f049e8f3c22.png)


Note that it gives no guidance for "unpickable" dates.

@jamin-hall -- help?




The style guide has this in it:

![datepicker 2015-02-11 13 08 19](https://cloud.githubusercontent.com/assets/362417/6152976/24fba7b0-b1ef-11e4-9bf3-82f641ec35d1.png)

![datepicker 2015-02-11 13 09 08](https://cloud.githubusercontent.com/assets/362417/6152989/3713ef84-b1ef-11e4-9c2b-127231200e40.png)

![datepicker 2015-02-11 13 09 40](https://cloud.githubusercontent.com/assets/362417/6152997/43a89a74-b1ef-11e4-9815-71f45c98a793.png)

![datepicker 2015-02-11 13 10 05](https://cloud.githubusercontent.com/assets/362417/6153008/53f35cb6-b1ef-11e4-8472-c926dcd504dd.png)

**Comment by mbeard** [comment]
@jamin-hall do we have guidance on styling for blackout dates?

**Comment by jamin-hall** [comment]
Sure. This wasn't detailed out in the style guide, but looking more closely the border and text color should be #EEE. See the 'Various States' screenshot for an example where Sept. 1st and 2nd are blacked out. Doesn't seem like this was apparent at a glance, so maybe we need to consider additional styling changes.


JAMIN HALL
Lead Interaction Designer | salesforce.com
Mobile: 317-701-4990

**Comment by mbeard** [comment]
Upon further consideration of this.  Is there any reason that when allowPastDate is set to false, effectively a past date is the equivalent of a restricted date - right?

These scenarios do not look or behave the same way currently.

**Comment by mbeard** [comment]
Here are the changes needed:
1. Remove disabled appearance of past dates when `allowPastDates:true`
2. Leave disabled appearance of past dates when `allowPastDates:false`
3. Update appearance of restricted dates to be the same as a past date when `allowPastDates:false`
