### ISSUE TITLE
banner icons should not include a border

### ISSUE THREAD

**Issue by swilliamset** [ExactTarget/fuelux-mctheme#92]
This is required to match original styleguide.

Icons in question:
https://github.com/ExactTarget/fuelux-mctheme/blob/master/img/spritesheet.png
https://github.com/ExactTarget/fuelux-mctheme/blob/master/img/spritesheet-2x.png
![screen shot 2014-12-10 at 2 50 41 pm](https://cloud.githubusercontent.com/assets/347227/5383068/3a2559be-807c-11e4-8ac1-7a032a791786.png)

**Comment by chriscorwin** [comment]
Got it.

As soon as I get to these, I'll make sure to follow the [style guide](https://smc-uxa.slack.com/files/swilliams/F03ADKBPV/et_controls_library_text_color_updates_oct-28-2011_v2.pdf) rather than the existing sprite.

**Comment by chriscorwin** [comment]
Fixed in #133
